apiVersion: apps/v1
kind: Deployment
metadata:
  name: ether-website
  labels:
    app: ether-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ether-website
  template:
    metadata:
      labels:
        app: ether-website
    spec:
      containers:
        - name: ether-website
          image: ghcr.io/YOUR_ORG/ether-website:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: production
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
