apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ether-website
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ether.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ether-website
                port:
                  number: 80
