apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: ether
type: Opaque
stringData:
  credentials.json: |
    {"AccountTag":"7a369d7978791b024778fca489659257","TunnelSecret":"kZuSvs58VMWXl+46DY4jePotrZuITN15HFqa83Xl79w=","TunnelID":"215901ec-f772-4636-a158-d64d08a1476c","Endpoint":""}
